---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - employee.appscode.com
  resources:
  - employees
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - employee.appscode.com
  resources:
  - employees/finalizers
  verbs:
  - update
- apiGroups:
  - employee.appscode.com
  resources:
  - employees/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - other.appscode.com
  resources:
  - employees
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - other.appscode.com
  resources:
  - employees/finalizers
  verbs:
  - update
- apiGroups:
  - other.appscode.com
  resources:
  - employees/status
  verbs:
  - get
  - patch
  - update
