apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pv-claim
  namespace: appscode
spec:
  storageClassName: standard2
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi